export const FETCH_GROUP_ITEMS_REQUEST = 'FETCH_GROUP_ITEMS_REQUEST'
export const FETCH_GROUP_ITEMS_SUCCESS = 'FETCH_GROUP_ITEMS_SUCCESS'
export const FETCH_GROUP_ITEMS_FAILURE = 'FETCH_GROUP_ITEMS_FAILURE'
export const UPDATE_GROUPS = 'UPDATE_GROUPS'

export const FETCH_GROUP_DETAILS_REQUEST = 'FETCH_GROUP_DETAILS_REQUEST'

export const SET_GROUPS_BY_NAME_FILTER = 'SET_GROUPS_BY_NAME_FILTER'
export const SELECT_GROUP_DETAILS = 'SELECT_GROUP_DETAILS'

export const UPDATE_USERS = 'UPDATE_USERS'
export const SET_USERS_BY_NAME_FILTER = 'SET_USERS_BY_NAME_FILTER'
export const SELECT_USER_DETAILS = 'SELECT_USER_DETAILS'

export const FETCH_AUTH_REQUEST = 'FETCH_AUTH_REQUEST'
export const FETCH_AUTH_SUCCESS = 'FETCH_AUTH_SUCCESS'
export const FETCH_AUTH_FAILURE = 'FETCH_AUTH_FAILURE'
export const RECEIVE_AUTH = 'RECEIVE_AUTH'