export const FETCH_GROUP_ITEMS_REQUEST = 'FETCH_GROUP_ITEMS_REQUEST'
export const FETCH_GROUP_ITEMS_SUCCESS = 'FETCH_GROUP_ITEMS_SUCCESS'
export const FETCH_GROUP_ITEMS_FAILURE = 'FETCH_GROUP_ITEMS_FAILURE'
